services:
  spring:
    build: .
    container_name: ncp-server
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RAG_EMBEDDING_BASE_URL: ${RAG_EMBEDDING_BASE_URL}
      FASTAPI_CHAT_URL: ${FASTAPI_CHAT_URL}
      NAVER_MAPS_CLIENT_ID: ${NAVER_MAPS_CLIENT_ID}
      NAVER_MAPS_CLIENT_SECRET: ${NAVER_MAPS_CLIENT_SECRET}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_REDIRECT_URI: ${NAVER_REDIRECT_URI}
      NCP_CLIENT_ID: ${NCP_CLIENT_ID}
      NCP_CLIENT_SECRET: ${NCP_CLIENT_SECRET}
    restart: unless-stopped