spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  forward-headers-strategy: framework

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS z, Asia/Seoul} %5p [%t] %logger{36} : %msg%n"
  level:
    root: INFO
    com.ncp.team3: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
